actions:
  1:
    action: delete_indices
    description: >-
      Delete indices.  Find which to delete by first limiting the list to logstash-
      prefixed indices. Next filter by space, to those indices in excess of
      20g of usage.  Then further filter those to prevent deletion of anything
      less than 7 days old.
    options:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: space
      disk_space: 20
      use_age: True
      source: creation_date
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 7
